modLoader="javafml"
loaderVersion="[35,)"
license="TODO: creative commons"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="gramophone"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}"
displayName="Immersive Gramophone"
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="http://example.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
#credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors="Keykeepers Interactive"
description='''
Immersive Gramophone

Adds a few pieces of technology that are appropriate to the spirit and aesthetics of Immersive Engineering. The tech
interfaces together in a way that lays a foundation for a future mod by this author, but can still be used in a
standalone fashion.
'''

[[dependencies.gramophone]]
  modId="immersiveengineering"
  mandatory=true
  versionRange="[1.16.4,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.gramophone]]
  modId="forge"
  mandatory=true
  versionRange="[${forge_version},)"
  ordering="NONE"
  side="BOTH"

[[dependencies.gramophone]]
  modId="minecraft"
  mandatory=true
  versionRange="[${mc_version}]"
  ordering="NONE"
  side="BOTH"
